"""initial schema

Revision ID: b3cf36a9c905
Revises: 
Create Date: 2026-10-01 16:55:30.442427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3cf36a9c905'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('keyword_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_by', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('keyword_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keyword_sets_is_active'), ['is_active'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('new_relevant', sa.Integer(), nullable=False),
    sa.Column('new_review', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_settings',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_nonzero_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=30), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)

    op.create_table('run_source_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('source_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_from', sa.Date(), nullable=True),
    sa.Column('window_to', sa.Date(), nullable=True),
    sa.Column('queries_total', sa.Integer(), nullable=False),
    sa.Column('queries_done', sa.Integer(), nullable=False),
    sa.Column('found', sa.Integer(), nullable=False),
    sa.Column('new', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_source_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_source_stats_run_id'), ['run_id'], unique=False)

    op.create_table('tenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eis_number', sa.String(length=64), nullable=True),
    sa.Column('dedup_key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('customer_name', sa.Text(), nullable=False),
    sa.Column('customer_inn', sa.String(length=12), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('delivery_place', sa.Text(), nullable=False),
    sa.Column('law', sa.String(length=20), nullable=False),
    sa.Column('procedure_type', sa.String(length=255), nullable=True),
    sa.Column('nmck', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('application_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('okpd2_codes', sa.JSON(), nullable=False),
    sa.Column('positions', sa.JSON(), nullable=False),
    sa.Column('notice_text', sa.Text(), nullable=False),
    sa.Column('relevance', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('matches', sa.JSON(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('classification_reasons', sa.JSON(), nullable=False),
    sa.Column('keyword_set_id', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.Column('is_updated', sa.Boolean(), nullable=False),
    sa.Column('change_log', sa.JSON(), nullable=False),
    sa.Column('user_status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_set_id'], ['keyword_sets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eis_number')
    )
    with op.batch_alter_table('tenders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenders_customer_inn'), ['customer_inn'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenders_dedup_key'), ['dedup_key'], unique=False)
        batch_op.create_index('ix_tenders_is_new', ['is_new'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenders_relevance'), ['relevance'], unique=False)
        batch_op.create_index('ix_tenders_relevance_deadline', ['relevance', 'application_deadline'], unique=False)

    op.create_table('tender_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('source_code', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_code', 'external_id', name='uq_tender_sources_source_external')
    )
    with op.batch_alter_table('tender_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tender_sources_tender_id'), ['tender_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tender_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tender_sources_tender_id'))

    op.drop_table('tender_sources')
    with op.batch_alter_table('tenders', schema=None) as batch_op:
        batch_op.drop_index('ix_tenders_relevance_deadline')
        batch_op.drop_index(batch_op.f('ix_tenders_relevance'))
        batch_op.drop_index('ix_tenders_is_new')
        batch_op.drop_index(batch_op.f('ix_tenders_dedup_key'))
        batch_op.drop_index(batch_op.f('ix_tenders_customer_inn'))

    op.drop_table('tenders')
    with op.batch_alter_table('run_source_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_source_stats_run_id'))

    op.drop_table('run_source_stats')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    op.drop_table('source_settings')
    op.drop_table('runs')
    with op.batch_alter_table('keyword_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keyword_sets_is_active'))

    op.drop_table('keyword_sets')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
