"""source revision

Revision ID: 5fb1dc1ada4b
Revises: b3cf36a9c905
Create Date: 2026-10-02 07:57:51.081422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb1dc1ada4b'
down_revision: Union[str, Sequence[str], None] = 'b3cf36a9c905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tender_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revision', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tender_sources', schema=None) as batch_op:
        batch_op.drop_column('revision')

    # ### end Alembic commands ###
